### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#1]
It's recognizing my chrome/computer desktop as HD Tablet/Phone and my samsung galaxy s5 as > Desktop 

.. setting I overlooked maybe?

**Comment by kmhcreative** [comment]
The original "Phones & Tablets" stylesheet stops at 1024 px wide because that's what iPad renders in landscape.  Which, yes, did cause most Android tablets to show ZappBars in portrait but not in landscape.

I updated the Settings to make it more obvious it's by screen size and there is now a "Tablet" setting that goes up to 1280 pixels wide (which should capture 720p tablets) and the "HD Tablets" has been adjusted so it should capture tablets up to the Surface 3 Pro.  But I also added additional options that let you target either "All Devices," "Only Mobile Devices," or use screen size for desktops and/or "Force" mobile devices to use ZappBars regardless of screen size.  (Since I brought it up, though, I suppose I should point out that the Microsoft Surface tablets are not detected as "mobile" devices since they identify themselves essentially the same as a Windows laptop).

So, if you set the Device options to "Force Mobile" they should appear on your tablet in both orientations, or you can set the screen size targeting wide enough to include your tablet in landscape.
