### ISSUE TITLE
ComicPress 4.3 and Zappbar

### ISSUE THREAD

**Issue by Frumph** [kmhcreative/zappbar#6]
https://github.com/Frumph/comicpress
- Breaks,  there are new 'controllable' customizer options which control design layout for the #page #sidebar-left and #sidebar-right widths, as well as those sections are now display: table-cell; with #subcontent-wrapper { display: table; }

**Comment by kmhcreative** [comment]
Ok, edited site tweaks, retrofit, and targeting stylesheets to reflect those changes.  Also added some tweaks for the theme header, menu, and schemes work better when scaled down for mobile screens.

If you select "Make theme responsive even when ZappBars are not displayed," that uses the "retrofit.css" static stylesheet instead of generated css (and also doesn't use the ZappBar screen size settings).  I left it set up to kick in with responsive overrides below 980px wide, but commented the 2 places you'd need to change it if using some other default width.  (Technically, if all you wanted to do was override the theme to make the layout responsive you'd only need is that "retrofit" stylesheet).

If the ZappBars are being applied, though, that uses generated css and a different static stylesheet (site_tweaks.css) so that shouldn't need anything edited in it to make it work.

**Comment by Frumph** [comment]
^ This is why I set you as being able to read/write as a collaborator on the comicpress github, .. did you get my email about that?   I really could use your opinion on what would be best and the help with it.

**Comment by Frumph** [comment]
Well one of the reasons, the other is your coding is amazing, and I think your involvement could do some sweet things with the theme.

**Comment by Frumph** [comment]
Yeah, still breaks the customizer control of site width and permanently makes it 980px;  I do read that I would need to change that someplace?  Assuming you meant hardcoded in those stylesheets; any values that I  can use in an override generated by chance?

`$page_width = intval(get_theme_mod('comicpress-customize-range-site-width', 980));`

**Comment by kmhcreative** [comment]
The two places are on line 37 of "retrofit.css" it sets a "max-width: 980px" and then the media query at line 181 is set to move sidebars above/below when window is "979px" or narrower.

Over-riding the max-width would be easy with just a "max-width: 1280 !important;" and over-riding the media query block just below that width (or whatever wider width) would be easy too - so long as the over-ride was enqueued/written later in the page, but that wouldn't work for widths narrower than 979px.

The only real way around this is to not use a static file but dynamically write the "retrofit" stylesheet like the ZappBar one already does (though a "retrofit" version would be much, much simpler).  I'll put one together.

I've been reluctant to edit the actual ComicPress parent theme stylesheet because I'm not sure what the consequences might be to peoples' customized child themes.  It would probably be better to modify the blank child theme for responsive layout so nobody's existing child themes are adversely affected by any layout changes.  Or is this next ComicPress release breaking backwards-compatibility anyway?

**Comment by Frumph** [comment]
4.3 of comicpress is billed to have major stylesheet information added/changed to it, so probably the best time to do it ;/

**Comment by Frumph** [comment]
besides i've almost made it completely responsive, just need to figure out the sidebar's when going below the 480 and why my phone doesn't responsive it when your plugins not active ;/

**Comment by kmhcreative** [comment]
The reason your phone probably isn't going responsive without my plugin is that ZappBar also adds some mobile meta tags to the head.  Without those mobile browsers will just zoom it as a web page.

Back to the original post, since my retrofit overrides it with "display: block;" I am kind of curious what the reasoning was behind changing those elements to "display: table;" and "display: table-cell"?  I ask because I would typically only use table rendering for a layout container if:
1. I wanted the container to automatically expand/collapse to contain the content without scrollbars (except you have specific widths on them) or
2. I wanted to vertically center something inside of them in a way that was backwards compatible for older browsers (otherwise I'd probably use a flexbox for a more modern approach).

**Comment by Frumph** [comment]
the #content-column becomes a variable width and allows me to use a single #page variable to shrink and grow the site which it does on the fly, using table-cell's allow them to stay in position where they need to be and the static width on the sidebars allows again the #content to grow and shrink as needed

**Comment by Frumph** [comment]
If someone wanted to change the width say of the right sidebar, they'd first do the override, then they'd have to calculate the math to change #content-column to be proper width and more .. trying to make it as simplistic as possible for non-css end users

**Comment by Frumph** [comment]
... had to remove that anyways, firefox has a bug with it that made it bad to use.   So it's revertted to fixed widths again but on a good note it's all still generated with the sliders in the customizer.
